version: '3.8'

services:
  # Twilio 专属数据库
  twilio_db:
    image: postgres:15-alpine
    container_name: twilio_db
    restart: always
    environment:
      POSTGRES_USER: twilio_user
      POSTGRES_PASSWORD: twilio_password
      POSTGRES_DB: twilio_database
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      # 外部连接端口 (给 pgAdmin 用的)
      - "5436:5432"
    networks:
      - twilio_net

  # Twilio App
  twilio_app:
    build: .
    container_name: twilio_app
    restart: always
    depends_on:
      - twilio_db
    ports:
      # 浏览器访问端口
      - "3004:3000"
    environment:
      - PORT=3000
      - TOKEN_KEY=fb0dd4aecd80cb833366b8854571e580fbc741f96d65cd2345857cafcf8ef29f
      # 数据库连接
      - DB=postgres://twilio_user:twilio_password@twilio_db:5432/twilio_database
      # Twilio 账号信息 (填你真实的)
      - TWILIO_ACCOUNT_SID=AC4cd23e0f6054e21ad8184fe83727e537
      - TWILIO_AUTH_TOKEN=694968a6e0e59886c90573e2b6518f8d
      - TWILIO_TWIML_APP_SID=APdab304687f0203b402fdbf74f3367c74
      - TWILIO_API_KEY=SKfc4bf221e68f73dc2bb8f673d0b6257c
      - TWILIO_API_SECRET=EER7QnWu5S7aU2PsNyvJvJw22ZS99SzS
      - BASE_URL=http://77.110.105.223:3004
      # ⚠️ 记得把代码里的网址改成这个 IP:3004
    networks:
      - twilio_net

networks:
  twilio_net: